from manim import *
import numpy as np
class OpeningManimExample(Scene):
    def construct(self):
        
        name = Text("Imaginary Number = 'i'").shift(UP*3.3).scale(.5)
        name.set_color_by_gradient(BLUE, WHITE)
        name2 = Text("Let's test putting 'i' into the equation").shift(UP*2.7).scale(.5)
        name2.set_color_by_gradient(BLUE, WHITE)
        equation = MathTex(r"e^{ix} = 1 + ix +\frac{1}{2!}(ix)^{2} +\frac{1}{3!}(ix)^{3}+\frac{1}{4!}(ix)^{4}+\frac{1}{5!}(ix)^{5}+ \frac{1}{6!}(ix)^{6} +\frac{1}{7!}i^{7}(ix)^{7}.....", tex_to_color_map={"x": RED}).shift(UP*1.9).scale(.7)
        equation2 = MathTex(r"e^{ix} = 1 + ix +\frac{1}{2!}i^{2}x^{2} +\frac{1}{3!}i^{3}x^{3}+\frac{1}{4!}i^{4}x^{4}+\frac{1}{5!}i^{5}x^{5}+ \frac{1}{6!}i^{6}x^{6} +\frac{1}{6!}i^{7}x^{7}.....", tex_to_color_map={"x": RED}).shift(UP*1.9).scale(.7)
        name3 = Text(".................(16)").shift(RIGHT*4).shift(UP*1.5).scale(.4)
        name4 = Text("Now,").to_edge(LEFT).shift(UP*.7).scale(.5)
        equation3 = MathTex(r"i^{2} = -1").to_edge(LEFT).scale(.6)
        equation4 = MathTex(r"i^{3} = i^{2} \cdot i = -i").to_edge(LEFT).shift(DOWN*.5).scale(.6)
        equation5 = MathTex(r"i^{4} = i^{2} \cdot i^{2} = 1").to_edge(LEFT).shift(DOWN*1).scale(.6)
        equation6 = MathTex(r"i^{5} = i^{4} \cdot i = i").to_edge(LEFT).shift(DOWN*1.5).scale(.6)
        equation7 = MathTex(r"i^{6} = (i^{2})^{3} = -1").to_edge(LEFT).shift(DOWN*2).scale(.6)
        equation8 = MathTex(r"i^{7} = i^{6} \cdot i = -i").to_edge(LEFT).shift(DOWN*2.5).scale(.6)
        name5 = Text("Putting these in (16)...").shift(UP*.4).scale(.5)
        equation10 = MathTex(r"e^{ix} = 1 + ix -\frac{1}{2!}x^{2} -i\frac{1}{3!}x^{3}+\frac{1}{4!}x^{4} + i\frac{1}{5!}x^{5} -\frac{1}{6!}x^{6}-i\frac{1}{7!}x^{7}.....", tex_to_color_map={"x": RED}).shift(RIGHT*.6).shift(DOWN*.1).scale(.6)
        equation11 = MathTex(r"e^{ix} = (1 - \frac{1}{2!}x^{2} + \frac{1}{4!}x^{4} - \frac{1}{6!}x^{6} +...) + i(x - \frac{1}{3!}x^{3} + \frac{1}{5!}x^{5} - \frac{1}{7!}x^{7} +....) ", tex_to_color_map={"x": RED}).shift(RIGHT*.6).shift(DOWN*.3).scale(.6)
        rect = Rectangle(color = WHITE, height = .03, width = 3.6).shift(LEFT*1.2).shift(DOWN*.7)
        rect2 = Rectangle(color = WHITE, height = .5, width = 1.2).shift(LEFT*.4).shift(DOWN*2.5)
        arrow1 = Line(start=rect.get_bottom(), end=rect2.get_top(), buff=0.2).add_tip()
        rect3 = Rectangle(color = WHITE, height = .03, width = 3.6).shift(RIGHT*3.1).shift(DOWN*.7)
        rect4 = Rectangle(color = WHITE, height = .5, width = 1.2).shift(RIGHT*3).shift(DOWN*2.5)
        arrow2 = Line(start=rect3.get_bottom(), end=rect4.get_top(), buff=0.2).add_tip()
        equation12 = MathTex(r"cosx").shift(LEFT*.4).shift(DOWN*2.5).scale(.6)
        equation13 = MathTex(r"sinx").shift(RIGHT*3).shift(DOWN*2.5).scale(.6)
        equation14 = MathTex(r"e^{ix} = cosx + isinx", tex_to_color_map={"x": RED}).shift(RIGHT*2).shift(DOWN*3.5).scale(.8)
        equation15 = MathTex(r"e^{ix} = cosx + isinx", tex_to_color_map={"x": RED}).shift(RIGHT*2).shift(DOWN*3.5).scale(1)
        rect5 = Rectangle(color = WHITE, height = .7, width = 6).shift(RIGHT*2).shift(DOWN*3.5)




        self.play(Create(name),runtime=5)
        self.play(Create(name2),runtime=5)
        self.play(Write(equation),runtime=5)
        self.play(FadeTransform(equation, equation2),runtime=7)
        self.play(Create(name3),runtime=5)
        self.play(Create(name4),runtime=5)
        self.play(Write(equation3),runtime=5)
        self.play(Write(equation4),runtime=5)
        self.play(Write(equation5),runtime=5)
        self.play(Write(equation6),runtime=5)
        self.play(Write(equation7),runtime=5)
        self.play(Write(equation8),runtime=5)
        self.play(Create(name5),runtime=5)
        self.play(Write(equation10),runtime=5)
        self.play(FadeTransform(equation10, equation11),runtime=5)
        self.play(Create(rect),runtime=5)
        self.play(Create(arrow1),runtime=5)
        self.play(Create(rect2),runtime=5)
        self.play(Write(equation12),runtime=5)
        self.play(Create(rect3),runtime=5)
        self.play(Create(arrow2),runtime=5)
        self.play(Create(rect4),runtime=5)
        self.play(Write(equation13),runtime=5)
        self.play(Write(equation14),runtime=5)
        self.play(FadeTransform(equation14, equation15),runtime=5)
        self.play(Create(rect5),runtime=5)
        self.wait(5)